# BACKGROUND
background {
    path = screenshot
    blur_passes = 2
    blur_size = 2
    noise = 0
    vibrancy = 0
}

general {
    no_fade_in = true
    hide_cursor = true
    ignore_empty_input = true
}

# Time (Pixel / Minecraft Style - Putih Bersih)
label {
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(255, 255, 255, 1.0) # Warna Jam Putih Tegas
    font_size = 110
    font_family = Monocraft
    position = 0, 350
    halign = center
    valign = center
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
    animation = inputFieldColors, 1, 2, linear
}

# Profile-Photo (Aksen Pink Pita Chitoge pada Ring/Border)
image {
    path = ~/.config/hypr/assets/chitoge.jpeg
    fade_in = 0.5
    fade_out = 0.5
    outer_color = rgba(255, 107, 139, 0.8) # Pink Pita
    inner_color = rgba(18, 18, 24, 0.6)   # Hitam Transparan
    border_size = 2
    size = 100
    rounding = -1 # Bikin foto jadi bundar sempurna
    position = 0, 10
    halign = center
    valign = center
}

# Input Field (Kuning Rambut + Pink Pita + Hitam + Teks Putih)
input-field {
    size = 350, 50
    outline_thickness = 3
    
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    
    # Warna Border & Background
    outer_color = rgba(255, 224, 102, 1.0) rgba(255, 107, 139, 1.0) 45deg # Gradient Kuning & Pink
    inner_color = rgba(18, 18, 24, 0.85)                          # Background Hitam Pekat
    
    # Warna Teks & Indikator
    font_color = rgb(255, 255, 255)       # Teks saat ngetik warna Putih
    check_color = rgb(255, 224, 102)      # Kuning saat cek password
    fail_color = rgb(255, 77, 109)        # Pink/Merah kalau password salah
    
    fade_on_empty = false
    font_family = Monocraft
    font_size = 30
    placeholder_text = <i><span foreground="##ffffffaa">Enter the password</span></i> # Placeholder Putih Transparan
    hide_input = false
    position = 0, -170
    halign = center
    valign = center
}