# Preload image into RAM for faster loading
preload = /home/bernad/.config/hypr/assets/nino.jpg

# Set the preloaded image to a specific monitor
wallpaper = eDP-1,/home/bernad/.config/hypr/assets/nino.png

# Leave monitor field empty as a fallback for all other monitors
# wallpaper = ,/home/username/Pictures/wallpaper.png

# Enable or disable the Hyprland splash text over the wallpaper
splash = false
